version: "3"

services:
  mongodb:
    image: mongo:5.0
    # environment:
    #   - MONGODB_DATABASE="test"
    ports:
      - 27017:27017

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017