name: Coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install and test:cov
      run: |
        yarn install
        yarn add codecov --dev
        yarn test:cov
        ./node_modules/.bin/codecov # https://github.com/codecov/codecov-node
